### ISSUE TITLE
Typo in s6-boot/PKGBUILD

### ISSUE THREAD

**Issue by multiplexd** [Obarun/obarun-pkgbuild#1]
Line 41 in the PKGBUILD for s6-boot is:
```
install -dm 0755 "$pkdir/etc/s6-serv/enabled/rc/source"
```
`$pkdir` should be `$pkgdir`

The PKGBUILD tries to create the directory /etc/s6-serv on the host system, which results in a permission denied error, as the variable `$pkdir` is undefined.

**Comment by Obarun** [comment]
shame on me!! many thanks for this feedback, this was rectified.
